FROM node:16-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ENV OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID}
ENV OAUTH_SECRET=${OAUTH_SECRET}
ENV DEVELOPER_TOKEN=${DEVELOPER_TOKEN}
ENV REFRESH_TOKEN=${REFRESH_TOKEN}
ENV GCLOUD_SERVICE_ACCOUNT_KEY='${GCLOUD_SERVICE_ACCOUNT_KEY}'
ENV TZ=Asia/Calcutta

CMD ["node", "index.js"]